In [1]:
import os, os.path
from estnltk.storage.postgres import PostgresStorage

In [ ]:
pgpass_file = 'pgpass.txt'
assert os.path.exists(pgpass_file)

storage = PostgresStorage(pgpass_file=pgpass_file, schema='koondkorpus', role='koondkorpus_read')

In [3]:
# Info olemasolevate kollektsioonide kohta
storage.collections

['koondkorpus_base_subset_of_5000_v2',
 'koondkorpus_base_v2',
 'koondkorpus_sentences',
 'koondkorpus_sentences_test_5000_sg_thread',
 'koondkorpus_syntax_subset',
 'koondkorpus_words_v16_1']

In [ ]:
# Võtame ette lausete testkollektsiooni
collection = storage['koondkorpus_sentences_test_5000_sg_thread']
collection

In [5]:
# kollektsiooni kihid
collection.layers

['words',
 'sentences',
 'compound_tokens',
 'morph_extended',
 'morph_analysis',
 'tokens',
 'v171_named_entities',
 'v172_geo_terms',
 'v172_stanza_syntax',
 'v172_pre_timexes',
 'v172_clauses',
 'v172_advmod_phrases',
 'v172_obl_phrases']

In [6]:
# Näide: Üle kollektsiooni itereerimine (10 esimest lauset koos nimeüksuste ja süntaksiga):
for text_id, text_obj in collection.select(layers=['v171_named_entities', 'v172_stanza_syntax', 'morph_analysis']).head(10):
    if len(text_obj['v171_named_entities']) > 0:
        print(text_id, text_obj.text)
        # Kuvame ainult laused, kus leidus nimeüksuseid
        display( text_obj['v171_named_entities'] )
        display( text_obj['v172_stanza_syntax'] )

1 “ Kuulsus tabas mind kui hunnik telliskive , ” kurdab lapsevanemate hirm , miljoneid plaate müünud ja kümneid auhindu võitnud EMINEM , kes on nüüdseks vallutanud ka kinolina .

Layer(name='v171_named_entities', attributes=('nertag',), spans=SL[EnvelopingSpan(['EMINEM'], [{'nertag': 'PER'}])])

Layer(name='v172_stanza_syntax', attributes=('id', 'lemma', 'upostag', 'xpostag', 'feats', 'head', 'deprel', 'deps', 'misc', 'parent_span', 'children'), spans=SL[Span('“', [{'id': 1, 'lemma': '“', 'upostag': 'Z', 'xpostag': 'Z', 'feats': {}, 'head': 3, 'deprel': 'punct', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('Kuulsus', [{'id': 2, 'lemma': 'kuulsus', 'upostag': 'S', 'xpostag': 'S', 'feats': {'sg': 'sg', 'com': 'com', 'nom': 'nom'}, 'head': 3, 'deprel': 'nsubj', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('tabas', [{'id': 3, 'lemma': 'tabama', 'upostag': 'V', 'xpostag': 'V', 'feats': {'af': 'af', 'ps': 'ps', 'sg': 'sg', 'mod': 'mod', 'ps3': 'ps3', 'impf': 'impf', 'indic': 'indic'}, 'head': 0, 'deprel': 'root', 'deps': '_', 'misc': '_', 'parent_span': None, 'children': <class 'tuple'>}]),
Span('mind', [{'id': 4, 'lemma': 'mina', 'upostag': 'P', 'xpostag': 'P', 'feats': {'sg': 'sg', 'part': 'part'}, 'head': 3, 'deprel': 'obj', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('kui', [{'id': 5, 'lemma': 'kui', 'upostag': 'D', 'xpostag': 'D', 'feats': {}, 'head': 7, 'deprel': 'mark', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('hunnik', [{'id': 6, 'lemma': 'hunnik', 'upostag': 'S', 'xpostag': 'S', 'feats': {'sg': 'sg', 'com': 'com', 'nom': 'nom'}, 'head': 7, 'deprel': 'nmod', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('telliskive', [{'id': 7, 'lemma': 'telliskivi', 'upostag': 'S', 'xpostag': 'S', 'feats': {'pl': 'pl', 'com': 'com', 'part': 'part'}, 'head': 3, 'deprel': 'advcl', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': <class 'tuple'>}]),
Span(',', [{'id': 8, 'lemma': ',', 'upostag': 'Z', 'xpostag': 'Z', 'feats': {}, 'head': 3, 'deprel': 'punct', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('”', [{'id': 9, 'lemma': '”', 'upostag': 'Z', 'xpostag': 'Z', 'feats': {}, 'head': 3, 'deprel': 'punct', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('kurdab', [{'id': 10, 'lemma': 'kurtma', 'upostag': 'V', 'xpostag': 'V', 'feats': {'af': 'af', 'ps': 'ps', 'sg': 'sg', 'mod': 'mod', 'ps3': 'ps3', 'pres': 'pres', 'indic': 'indic'}, 'head': 3, 'deprel': 'parataxis', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': <class 'tuple'>}]),
Span('lapsevanemate', [{'id': 11, 'lemma': 'lapsevanem', 'upostag': 'S', 'xpostag': 'S', 'feats': {'pl': 'pl', 'com': 'com', 'gen': 'gen'}, 'head': 12, 'deprel': 'nmod', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('hirm', [{'id': 12, 'lemma': 'hirm', 'upostag': 'S', 'xpostag': 'S', 'feats': {'sg': 'sg', 'com': 'com', 'nom': 'nom'}, 'head': 10, 'deprel': 'nsubj', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': <class 'tuple'>}]),
Span(',', [{'id': 13, 'lemma': ',', 'upostag': 'Z', 'xpostag': 'Z', 'feats': {}, 'head': 16, 'deprel': 'punct', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('miljoneid', [{'id': 14, 'lemma': 'miljon', 'upostag': 'N', 'xpostag': 'N', 'feats': {'l': 'l', 'pl': 'pl', 'card': 'card', 'part': 'part'}, 'head': 15, 'deprel': 'nummod', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('plaate', [{'id': 15, 'lemma': 'plaat', 'upostag': 'S', 'xpostag': 'S', 'feats': {'pl': 'pl', 'com': 'com', 'part': 'part'}, 'head': 16, 'deprel': 'obj', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': <class 'tuple'>}]),
Span('müünud', [{'id': 16, 'lemma': 'müüma', 'upostag': 'V', 'xpostag': 'V', 'feats': {'ps': 'ps', 'mod': 'mod', 'neg': 'neg', 'impf': 'impf', 'indic': 'indic'}, 'head': 21, 'deprel': 'acl', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': <class 'tuple'>}]),
Span('ja', [{'id': 17, 'lemma': 'ja', 'upostag': 'J', 'xpostag': 'J', 'feats': {'crd': 'crd', 'sub': 'sub'}, 'head': 20, 'deprel': 'cc', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('kümneid', [{'id': 18, 'lemma': 'kümme', 'upostag': 'N', 'xpostag': 'N', 'feats': {'l': 'l', 'pl': 'pl', 'card': 'card', 'part': 'part'}, 'head': 19, 'deprel': 'nummod', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('auhindu', [{'id': 19, 'lemma': 'auhind', 'upostag': 'S', 'xpostag': 'S', 'feats': {'pl': 'pl', 'com': 'com', 'part': 'part'}, 'head': 20, 'deprel': 'obj', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': <class 'tuple'>}]),
Span('võitnud', [{'id': 20, 'lemma': 'võitma', 'upostag': 'V', 'xpostag': 'V', 'feats': {'ps': 'ps', 'mod': 'mod', 'neg': 'neg', 'impf': 'impf', 'indic': 'indic'}, 'head': 16, 'deprel': 'conj', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': <class 'tuple'>}]),
Span('EMINEM', [{'id': 21, 'lemma': 'Eminem', 'upostag': 'S', 'xpostag': 'S', 'feats': {'sg': 'sg', 'nom': 'nom', 'prop': 'prop'}, 'head': 12, 'deprel': 'conj', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': <class 'tuple'>}]),
Span(',', [{'id': 22, 'lemma': ',', 'upostag': 'Z', 'xpostag': 'Z', 'feats': {}, 'head': 26, 'deprel': 'punct', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('kes', [{'id': 23, 'lemma': 'kes', 'upostag': 'P', 'xpostag': 'P', 'feats': {'sg': 'sg', 'nom': 'nom'}, 'head': 26, 'deprel': 'nsubj', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('on', [{'id': 24, 'lemma': 'olema', 'upostag': 'V', 'xpostag': 'V', 'feats': {'af': 'af', 'ps': 'ps', 'sg': 'sg', 'aux': 'aux', 'ps3': 'ps3', 'pres': 'pres', 'indic': 'indic'}, 'head': 26, 'deprel': 'aux', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('nüüdseks', [{'id': 25, 'lemma': 'nüüdne', 'upostag': 'A', 'xpostag': 'A', 'feats': {'sg': 'sg', 'tr': 'tr', 'pos': 'pos'}, 'head': 26, 'deprel': 'obl', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('vallutanud', [{'id': 26, 'lemma': 'vallutama', 'upostag': 'V', 'xpostag': 'V', 'feats': {'ps': 'ps', 'mod': 'mod', 'past': 'past', 'partic': 'partic'}, 'head': 21, 'deprel': 'acl:relcl', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': <class 'tuple'>}]),
Span('ka', [{'id': 27, 'lemma': 'ka', 'upostag': 'D', 'xpostag': 'D', 'feats': {}, 'head': 28, 'deprel': 'advmod', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('kinolina', [{'id': 28, 'lemma': 'kinolina', 'upostag': 'S', 'xpostag': 'S', 'feats': {'sg': 'sg', 'com': 'com', 'nom': 'nom'}, 'head': 26, 'deprel': 'obj', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': <class 'tuple'>}]),
Span('.', [{'id': 29, 'lemma': '.', 'upostag': 'Z', 'xpostag': 'Z', 'feats': {}, 'head': 3, 'deprel': 'punct', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}])])

2 Kolme aastaga on Eminem  alias  Marshall Mathers III ( 30 ) kindlalt meie teadvusesse sööbinud .

Layer(name='v171_named_entities', attributes=('nertag',), spans=SL[EnvelopingSpan(['Mathers', 'III'], [{'nertag': 'PER'}])])

Layer(name='v172_stanza_syntax', attributes=('id', 'lemma', 'upostag', 'xpostag', 'feats', 'head', 'deprel', 'deps', 'misc', 'parent_span', 'children'), spans=SL[Span('Kolme', [{'id': 1, 'lemma': 'kolm', 'upostag': 'N', 'xpostag': 'N', 'feats': {'l': 'l', 'sg': 'sg', 'gen': 'gen', 'card': 'card'}, 'head': 2, 'deprel': 'nummod', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('aastaga', [{'id': 2, 'lemma': 'aasta', 'upostag': 'S', 'xpostag': 'S', 'feats': {'sg': 'sg', 'com': 'com', 'kom': 'kom'}, 'head': 15, 'deprel': 'obl', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': <class 'tuple'>}]),
Span('on', [{'id': 3, 'lemma': 'olema', 'upostag': 'V', 'xpostag': 'V', 'feats': {'af': 'af', 'pl': 'pl', 'ps': 'ps', 'aux': 'aux', 'ps3': 'ps3', 'pres': 'pres', 'indic': 'indic'}, 'head': 15, 'deprel': 'aux', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('Eminem', [{'id': 4, 'lemma': 'Eminem', 'upostag': 'S', 'xpostag': 'S', 'feats': {'sg': 'sg', 'nom': 'nom', 'prop': 'prop'}, 'head': 15, 'deprel': 'nsubj', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': <class 'tuple'>}]),
Span('alias', [{'id': 5, 'lemma': 'alias', 'upostag': 'Y', 'xpostag': 'Y', 'feats': {'nominal': 'nominal'}, 'head': 4, 'deprel': 'flat', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('Marshall', [{'id': 6, 'lemma': 'Marshall', 'upostag': 'S', 'xpostag': 'S', 'feats': {'sg': 'sg', 'nom': 'nom', 'prop': 'prop'}, 'head': 4, 'deprel': 'flat', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': <class 'tuple'>}]),
Span('Mathers', [{'id': 7, 'lemma': 'Mathers', 'upostag': 'S', 'xpostag': 'S', 'feats': {'sg': 'sg', 'nom': 'nom', 'prop': 'prop'}, 'head': 4, 'deprel': 'flat', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('III', [{'id': 8, 'lemma': 'III', 'upostag': 'N', 'xpostag': 'N', 'feats': {'<?>': '<?>', 'ord': 'ord', 'roman': 'roman'}, 'head': 6, 'deprel': 'flat', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('(', [{'id': 9, 'lemma': '(', 'upostag': 'Z', 'xpostag': 'Z', 'feats': {}, 'head': 10, 'deprel': 'punct', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('30', [{'id': 10, 'lemma': '30', 'upostag': 'N', 'xpostag': 'N', 'feats': {'<?>': '<?>', 'card': 'card', 'digit': 'digit'}, 'head': 4, 'deprel': 'parataxis', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': <class 'tuple'>}]),
Span(')', [{'id': 11, 'lemma': ')', 'upostag': 'Z', 'xpostag': 'Z', 'feats': {}, 'head': 10, 'deprel': 'punct', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('kindlalt', [{'id': 12, 'lemma': 'kindlalt', 'upostag': 'D', 'xpostag': 'D', 'feats': {}, 'head': 15, 'deprel': 'advmod', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('meie', [{'id': 13, 'lemma': 'mina', 'upostag': 'P', 'xpostag': 'P', 'feats': {'pl': 'pl', 'gen': 'gen'}, 'head': 14, 'deprel': 'nmod', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('teadvusesse', [{'id': 14, 'lemma': 'teadvus', 'upostag': 'S', 'xpostag': 'S', 'feats': {'sg': 'sg', 'com': 'com', 'ill': 'ill'}, 'head': 15, 'deprel': 'obl', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': <class 'tuple'>}]),
Span('sööbinud', [{'id': 15, 'lemma': 'sööbinud', 'upostag': 'A', 'xpostag': 'A', 'feats': {'pos': 'pos'}, 'head': 0, 'deprel': 'root', 'deps': '_', 'misc': '_', 'parent_span': None, 'children': <class 'tuple'>}]),
Span('.', [{'id': 16, 'lemma': '.', 'upostag': 'Z', 'xpostag': 'Z', 'feats': {}, 'head': 15, 'deprel': 'punct', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}])])

7 “ Kuulsus tabas mind kui hunnik telliskive , ” räägib Eminem .

Layer(name='v171_named_entities', attributes=('nertag',), spans=SL[EnvelopingSpan(['Eminem'], [{'nertag': 'PER'}])])

Layer(name='v172_stanza_syntax', attributes=('id', 'lemma', 'upostag', 'xpostag', 'feats', 'head', 'deprel', 'deps', 'misc', 'parent_span', 'children'), spans=SL[Span('“', [{'id': 1, 'lemma': '“', 'upostag': 'Z', 'xpostag': 'Z', 'feats': {}, 'head': 3, 'deprel': 'punct', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('Kuulsus', [{'id': 2, 'lemma': 'kuulsus', 'upostag': 'S', 'xpostag': 'S', 'feats': {'sg': 'sg', 'com': 'com', 'nom': 'nom'}, 'head': 3, 'deprel': 'nsubj', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('tabas', [{'id': 3, 'lemma': 'tabama', 'upostag': 'V', 'xpostag': 'V', 'feats': {'af': 'af', 'ps': 'ps', 'sg': 'sg', 'ps3': 'ps3', 'impf': 'impf', 'main': 'main', 'indic': 'indic'}, 'head': 0, 'deprel': 'root', 'deps': '_', 'misc': '_', 'parent_span': None, 'children': <class 'tuple'>}]),
Span('mind', [{'id': 4, 'lemma': 'mina', 'upostag': 'P', 'xpostag': 'P', 'feats': {'sg': 'sg', 'part': 'part'}, 'head': 3, 'deprel': 'obj', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('kui', [{'id': 5, 'lemma': 'kui', 'upostag': 'D', 'xpostag': 'D', 'feats': {}, 'head': 7, 'deprel': 'mark', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('hunnik', [{'id': 6, 'lemma': 'hunnik', 'upostag': 'S', 'xpostag': 'S', 'feats': {'sg': 'sg', 'com': 'com', 'nom': 'nom'}, 'head': 7, 'deprel': 'nmod', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('telliskive', [{'id': 7, 'lemma': 'telliskivi', 'upostag': 'S', 'xpostag': 'S', 'feats': {'pl': 'pl', 'com': 'com', 'part': 'part'}, 'head': 3, 'deprel': 'advcl', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': <class 'tuple'>}]),
Span(',', [{'id': 8, 'lemma': ',', 'upostag': 'Z', 'xpostag': 'Z', 'feats': {}, 'head': 3, 'deprel': 'punct', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('”', [{'id': 9, 'lemma': '”', 'upostag': 'Z', 'xpostag': 'Z', 'feats': {}, 'head': 3, 'deprel': 'punct', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('räägib', [{'id': 10, 'lemma': 'rääkima', 'upostag': 'V', 'xpostag': 'V', 'feats': {'af': 'af', 'ps': 'ps', 'sg': 'sg', 'mod': 'mod', 'ps3': 'ps3', 'pres': 'pres', 'indic': 'indic'}, 'head': 3, 'deprel': 'parataxis', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': <class 'tuple'>}]),
Span('Eminem', [{'id': 11, 'lemma': 'Eminem', 'upostag': 'S', 'xpostag': 'S', 'feats': {'sg': 'sg', 'nom': 'nom', 'prop': 'prop'}, 'head': 10, 'deprel': 'nsubj', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('.', [{'id': 12, 'lemma': '.', 'upostag': 'Z', 'xpostag': 'Z', 'feats': {}, 'head': 3, 'deprel': 'punct', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}])])

In [ ]:
# Pärast töö lõppu sulge ühendus
storage.close()